### ISSUE TITLE
Doesn't discover multiple test suites

### ISSUE THREAD

**Issue by sgillespie** [bennofs/tasty-th#10]
I have 2 test suites, both of them use `testGroupGenerator`. One of them executes tests, the other does not. Have a look at my cabal package:

https://github.com/sgillespie/elocrypt/blob/6ea4f0c1ab3550e069427c804527c0fb0fbd0f40/elocrypt.cabal

You can see the output of the test here:

https://travis-ci.org/sgillespie/elocrypt/builds/220181604#L210

You can see that it's not executing any tests for the second suite (ui-tests). However, if I downgrade to version 0.1.4, it executes both suites.

**Comment by bennofs** [comment]
It looks like haskell-src-exts generates `FunBind` and not `PatBind` for functions like `f x = ...`. I'll write some test cases and fix this.

**Comment by bennofs** [comment]
Should be fixed now. I added some tests to ensure it works correctly, and will release a fixed `0.1.7` shortly.
